"""empty message

Revision ID: 0b7d7bc23bfb
Revises: e981ae3ea5de
Create Date: 2020-09-24 11:48:17.378032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b7d7bc23bfb'
down_revision = 'e981ae3ea5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry_tbl', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('enquiry_tbl', sa.Column('lon', sa.Float(), nullable=True))
    op.drop_column('enquiry_tbl', 'lon_')
    op.drop_column('enquiry_tbl', 'lat_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiry_tbl', sa.Column('lat_', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('enquiry_tbl', sa.Column('lon_', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('enquiry_tbl', 'lon')
    op.drop_column('enquiry_tbl', 'lat')
    # ### end Alembic commands ###
