"""empty message

Revision ID: 0d517e3e7cf9
Revises: 95b69bfd1999
Create Date: 2020-09-19 14:36:16.057131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d517e3e7cf9'
down_revision = '95b69bfd1999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('image', sa.LargeBinary(), nullable=False))
    op.drop_column('image_model', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('image_model', 'image')
    # ### end Alembic commands ###
