"""empty message

Revision ID: 0e46ebb5aeca
Revises: 493f6f41a987
Create Date: 2020-09-06 17:53:07.810173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e46ebb5aeca'
down_revision = '493f6f41a987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'state_id')
    op.add_column('vehicles', sa.Column('company_mail', sa.String(length=100), nullable=True))
    op.drop_column('vehicles', 'company_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('company_email', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('vehicles', 'company_mail')
    op.add_column('cities', sa.Column('state_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
