"""empty message

Revision ID: 161767e4298a
Revises: fd734e131ed0
Create Date: 2020-09-20 17:18:09.494249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161767e4298a'
down_revision = 'fd734e131ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image_bin', sa.LargeBinary(), nullable=True))
    op.add_column('drivers', sa.Column('license_image_bin', sa.LargeBinary(), nullable=True))
    op.drop_column('drivers', 'image')
    op.drop_column('drivers', 'license_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('license_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'license_image_bin')
    op.drop_column('drivers', 'image_bin')
    # ### end Alembic commands ###
