"""empty message

Revision ID: 336574e0610d
Revises: fd62e5fd276f
Create Date: 2020-09-14 20:01:43.302873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336574e0610d'
down_revision = 'fd62e5fd276f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_vehicle_id_fkey', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'vehicle_tbl', ['vehicle_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key('drivers_vehicle_id_fkey', 'drivers', 'vehicle_tbl', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
