"""empty message

Revision ID: 3e29688f0856
Revises: 0b7d7bc23bfb
Create Date: 2020-10-05 11:36:45.065329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e29688f0856'
down_revision = '0b7d7bc23bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('refcode', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('refcode', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refcode')
    op.drop_column('owners', 'refcode')
    # ### end Alembic commands ###
