"""empty message

Revision ID: 48ddb29634ce
Revises: 9e9152219421
Create Date: 2020-09-18 19:43:11.804944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48ddb29634ce'
down_revision = '9e9152219421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model_tbl', sa.Column('status_bool', sa.Boolean(), nullable=True))
    op.drop_column('vehicle_model_tbl', 'status')
    op.add_column('vehicle_type_tbl', sa.Column('status_bool', sa.Boolean(), nullable=True))
    op.drop_column('vehicle_type_tbl', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type_tbl', sa.Column('status', postgresql.ENUM('active', 'inactive', name='status'), autoincrement=False, nullable=True))
    op.drop_column('vehicle_type_tbl', 'status_bool')
    op.add_column('vehicle_model_tbl', sa.Column('status', postgresql.ENUM('active', 'inactive', name='status'), autoincrement=False, nullable=True))
    op.drop_column('vehicle_model_tbl', 'status_bool')
    # ### end Alembic commands ###
