"""empty message

Revision ID: 4d48974b76ef
Revises: 48ddb29634ce
Create Date: 2020-09-18 19:45:56.162327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d48974b76ef'
down_revision = '48ddb29634ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model_tbl', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('vehicle_model_tbl', 'status_bool')
    op.add_column('vehicle_type_tbl', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('vehicle_type_tbl', 'status_bool')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type_tbl', sa.Column('status_bool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('vehicle_type_tbl', 'status')
    op.add_column('vehicle_model_tbl', sa.Column('status_bool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('vehicle_model_tbl', 'status')
    # ### end Alembic commands ###
