"""empty message

Revision ID: 51d9b936b067
Revises: ea333aea91eb
Create Date: 2020-10-15 19:44:43.987092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d9b936b067'
down_revision = 'ea333aea91eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tbl', sa.Column('cost', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_tbl', 'cost')
    # ### end Alembic commands ###
