"""empty message

Revision ID: 5722b42d8db6
Revises: 988701725475
Create Date: 2020-09-21 10:29:53.881847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5722b42d8db6'
down_revision = '988701725475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_vehicle_tbl', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_vehicle_tbl', 'image_url')
    # ### end Alembic commands ###
