"""empty message

Revision ID: 58d0aaedde8f
Revises: 161767e4298a
Create Date: 2020-09-20 17:21:38.805175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58d0aaedde8f'
down_revision = '161767e4298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('drivers', sa.Column('license', sa.LargeBinary(), nullable=True))
    op.drop_column('drivers', 'image_bin')
    op.drop_column('drivers', 'license_image_bin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('license_image_bin', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('image_bin', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'license')
    op.drop_column('drivers', 'image')
    # ### end Alembic commands ###
