"""empty message

Revision ID: 5eda9ceff134
Revises: a751c8229367
Create Date: 2020-09-08 18:30:39.508583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eda9ceff134'
down_revision = 'a751c8229367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type_tbl', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicle_type_tbl', 'master_vehicle_tbl', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_type_tbl', type_='foreignkey')
    op.drop_column('vehicle_type_tbl', 'master_id')
    # ### end Alembic commands ###
