"""empty message

Revision ID: 78fd6f8105a3
Revises: 135cca6e14f8
Create Date: 2020-09-19 14:42:22.741967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78fd6f8105a3'
down_revision = '135cca6e14f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('img', sa.LargeBinary(), nullable=True))
    op.drop_column('image_model', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('image_model', 'img')
    # ### end Alembic commands ###
