"""empty message

Revision ID: 81e0812a68e3
Revises: d2f4bce296e5
Create Date: 2020-09-14 11:41:02.824749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e0812a68e3'
down_revision = 'd2f4bce296e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('adhaar', sa.String(length=80), nullable=True))
    op.add_column('drivers', sa.Column('image', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_image', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('mobile2', sa.String(length=80), nullable=True))
    op.add_column('drivers', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'vehicle_tbl', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'vehicle_id')
    op.drop_column('drivers', 'owner_id')
    op.drop_column('drivers', 'mobile2')
    op.drop_column('drivers', 'license_image')
    op.drop_column('drivers', 'ip_address')
    op.drop_column('drivers', 'image')
    op.drop_column('drivers', 'adhaar')
    op.drop_column('drivers', 'added_on')
    # ### end Alembic commands ###
