"""empty message

Revision ID: 91e702507065
Revises: 5eda9ceff134
Create Date: 2020-09-12 18:27:18.125430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e702507065'
down_revision = '5eda9ceff134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('states_tbl')
    op.add_column('owners', sa.Column('full_address', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('gst', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('gumasta', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('mobile2', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('pan', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('pan_image', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('pin_code', sa.String(length=80), nullable=True))
    op.add_column('owners', sa.Column('tan', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'tan')
    op.drop_column('owners', 'pin_code')
    op.drop_column('owners', 'pan_image')
    op.drop_column('owners', 'pan')
    op.drop_column('owners', 'mobile2')
    op.drop_column('owners', 'gumasta')
    op.drop_column('owners', 'gst')
    op.drop_column('owners', 'full_address')
    op.create_table('states_tbl',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='states_tbl_pkey')
    )
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cities_pkey')
    )
    # ### end Alembic commands ###
