"""empty message

Revision ID: 95b69bfd1999
Revises: 4d48974b76ef
Create Date: 2020-09-19 14:25:20.782874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b69bfd1999'
down_revision = '4d48974b76ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('image', sa.BLOB(), nullable=False))
    op.drop_column('image_model', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('image_model', 'image')
    # ### end Alembic commands ###
