"""empty message

Revision ID: 988701725475
Revises: 58d0aaedde8f
Create Date: 2020-09-20 17:45:07.676767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988701725475'
down_revision = '58d0aaedde8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'license_filename')
    op.drop_column('drivers', 'image_filename')
    # ### end Alembic commands ###
