"""empty message

Revision ID: 9c211d20dc93
Revises: 91e702507065
Create Date: 2020-09-13 16:03:58.907138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c211d20dc93'
down_revision = '91e702507065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'owners', 'states_tbl', ['state_id'], ['id'])
    op.create_foreign_key(None, 'owners', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_column('owners', 'state_id')
    op.drop_column('owners', 'city_id')
    # ### end Alembic commands ###
