"""empty message

Revision ID: a2a8ec8c8477
Revises: a22b910ce87a
Create Date: 2020-09-13 17:30:02.568306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a8ec8c8477'
down_revision = 'a22b910ce87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_model_id', sa.Integer(), nullable=True),
    sa.Column('yom', sa.String(length=80), nullable=True),
    sa.Column('total_run_hrs', sa.Integer(), nullable=True),
    sa.Column('run_km_hr', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('rent_per_day', sa.Integer(), nullable=True),
    sa.Column('rent_per_hour', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('availibility', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('plate_no', sa.String(length=80), nullable=True),
    sa.Column('rc', sa.String(), nullable=True),
    sa.Column('invoice', sa.String(), nullable=True),
    sa.Column('insurance', sa.String(), nullable=True),
    sa.Column('busy_start', sa.String(length=80), nullable=True),
    sa.Column('busy_end', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_model_tbl.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_no')
    )
    op.drop_column('drivers', 'vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('vehicle', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_table('vehicle_tbl')
    # ### end Alembic commands ###
