"""empty message

Revision ID: aa1a1697b7bc
Revises: 48e86d40a587
Create Date: 2020-09-20 09:08:48.682678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1a1697b7bc'
down_revision = '48e86d40a587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_bin', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'image_bin')
    # ### end Alembic commands ###
