"""empty message

Revision ID: ca30f234d7b9
Revises: 5722b42d8db6
Create Date: 2020-09-23 07:29:37.758199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca30f234d7b9'
down_revision = '5722b42d8db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tbl', sa.Column('fuel_average_consumption_rate', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('fuel_consumption_rate', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('insurance_doc', sa.LargeBinary(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('invoice_doc', sa.LargeBinary(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rc_doc', sa.LargeBinary(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_day_with_fuel', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_day_without_fuel', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_hour_with_fuel', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_hour_without_fuel', sa.Integer(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image', sa.LargeBinary(), nullable=True))
    op.drop_column('vehicle_tbl', 'invoice')
    op.drop_column('vehicle_tbl', 'image')
    op.drop_column('vehicle_tbl', 'fuel')
    op.drop_column('vehicle_tbl', 'insurance')
    op.drop_column('vehicle_tbl', 'rent_per_day')
    op.drop_column('vehicle_tbl', 'rent_per_hour')
    op.drop_column('vehicle_tbl', 'rc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tbl', sa.Column('rc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rent_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('insurance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('fuel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle_tbl', sa.Column('invoice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vehicle_tbl', 'vehicle_image')
    op.drop_column('vehicle_tbl', 'rent_per_hour_without_fuel')
    op.drop_column('vehicle_tbl', 'rent_per_hour_with_fuel')
    op.drop_column('vehicle_tbl', 'rent_per_day_without_fuel')
    op.drop_column('vehicle_tbl', 'rent_per_day_with_fuel')
    op.drop_column('vehicle_tbl', 'rc_doc')
    op.drop_column('vehicle_tbl', 'invoice_doc')
    op.drop_column('vehicle_tbl', 'insurance_doc')
    op.drop_column('vehicle_tbl', 'fuel_consumption_rate')
    op.drop_column('vehicle_tbl', 'fuel_average_consumption_rate')
    # ### end Alembic commands ###
