"""empty message

Revision ID: df7d286b021d
Revises: 336574e0610d
Create Date: 2020-09-16 11:40:07.650313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7d286b021d'
down_revision = '336574e0610d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_vehicle_id_fkey', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'vehicle_tbl', ['vehicle_id'], ['id'])
    op.add_column('user', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    op.drop_column('user', 'google_id')
    op.drop_column('user', 'facebook_id')
    op.drop_column('user', 'added_on')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key('drivers_vehicle_id_fkey', 'drivers', 'vehicle_tbl', ['vehicle_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
