"""empty message

Revision ID: e04f77a5fc77
Revises: ca30f234d7b9
Create Date: 2020-09-23 09:25:56.573105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04f77a5fc77'
down_revision = 'ca30f234d7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_tbl', sa.Column('insurance_doc_name', sa.String(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('invoice_doc_name', sa.String(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('rc_doc_name', sa.String(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image_back', sa.LargeBinary(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image_back_name', sa.String(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image_name', sa.String(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image_side', sa.LargeBinary(), nullable=True))
    op.add_column('vehicle_tbl', sa.Column('vehicle_image_side_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_tbl', 'vehicle_image_side_name')
    op.drop_column('vehicle_tbl', 'vehicle_image_side')
    op.drop_column('vehicle_tbl', 'vehicle_image_name')
    op.drop_column('vehicle_tbl', 'vehicle_image_back_name')
    op.drop_column('vehicle_tbl', 'vehicle_image_back')
    op.drop_column('vehicle_tbl', 'rc_doc_name')
    op.drop_column('vehicle_tbl', 'invoice_doc_name')
    op.drop_column('vehicle_tbl', 'insurance_doc_name')
    # ### end Alembic commands ###
