"""empty message

Revision ID: ea333aea91eb
Revises: 4f15b461a2f5
Create Date: 2020-10-06 11:15:02.330748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea333aea91eb'
down_revision = '4f15b461a2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('tehsil', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'tehsil')
    # ### end Alembic commands ###
