"""empty message

Revision ID: ed22915c5656
Revises: 51d9b936b067
Create Date: 2020-10-21 16:23:31.866393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed22915c5656'
down_revision = '51d9b936b067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type_tbl', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_type_tbl', 'image_url')
    # ### end Alembic commands ###
