"""empty message

Revision ID: fc3c0638970f
Revises: 0e46ebb5aeca
Create Date: 2020-09-06 17:56:35.962001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3c0638970f'
down_revision = '0e46ebb5aeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'state_id')
    op.add_column('vehicles', sa.Column('company_mail', sa.String(length=100), nullable=True))
    op.drop_column('vehicles', 'company_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('company_email', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('vehicles', 'company_mail')
    op.add_column('cities', sa.Column('state_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
