"""empty message

Revision ID: fd62e5fd276f
Revises: 81e0812a68e3
Create Date: 2020-09-14 18:52:58.367831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd62e5fd276f'
down_revision = '81e0812a68e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicle_tbl_driver_id_fkey', 'vehicle_tbl', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('vehicle_tbl_driver_id_fkey', 'vehicle_tbl', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###
