"""empty message

Revision ID: fd734e131ed0
Revises: 9cdb9dbfb7f2
Create Date: 2020-09-20 09:53:00.543890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd734e131ed0'
down_revision = '9cdb9dbfb7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_name')
    # ### end Alembic commands ###
